(define
    (problem cube_test3x3)
    (:domain cube3)
    (:objects Y W B G O R)
    (:init
 
(cube1 Y G R)
(cube2 O W B)
(cube3 R Y B)
(cube4 O Y B)
(cube5 B W R)
(cube6 W R G)
(cube7 O W G)
(cube8 G O Y)
(edge12 W B)
(edge13 R W)
(edge15 Y G)
(edge24 O B)
(edge26 O W)
(edge34 Y B)
(edge37 Y O)
(edge48 G O)
(edge56 R G)
(edge57 B R)
(edge68 W G)
(edge78 Y R)
        
    )
    (:goal
        (and
            (cube1 R W B)
            (cube2 O W B)
            (cube3 R Y B)
            (cube4 O Y B)
            (cube5 R W G)
            (cube6 O W G)
            (cube7 R Y G)
            (cube8 O Y G)

            (edge12 W B)
            (edge24 O B)
            (edge34 Y B)
            (edge13 R B)

            (edge15 R W)
            (edge26 O W)
            (edge48 O Y)
            (edge37 R Y)

            (edge56 W G)
            (edge68 O G)
            (edge78 Y G)
            (edge57 R G)
 
        )
    )
)